### ISSUE TITLE
partly duplicated url-strings with query_hs

### ISSUE THREAD

**Issue by Xamk-DataLAB** [hsci-r/finnish-media-scrapers#10]
in some rare cases query_hs produces partly duplicated url-strings causing the fetch-hs cli tool to crash

<img width="390" alt="Näyttökuva 2021-12-2 kello 20 34 53" src="https://user-images.githubusercontent.com/75251830/144483317-57097d8c-749a-4315-a4ab-f4afecf59108.png">

**Comment by jiemakel** [comment]
Can you please supply a query word that causes these to appear? 

Our initial idea was to fix these by checking whether the URL already is complete at https://github.com/hsci-r/finnish-media-scrapers/blob/master/finnish_media_scrapers/query.py#L242, but all the links in the screenshot seem to also be broken at the source (do not lead to sensible articles even if fixed), so I can't verify the fix. 

(But now knowing that the HS search can return links to non-articles, we also need to make sure the fetch-hs tool gracefully handles these)

**Comment by Xamk-DataLAB** [comment]
I think the query was `fms-query-hs -f 2015-01-01 -t 2016-01-01 -o output.csv -q sote` but there were bad urls in newer queries too

**Comment by UMTti** [comment]
There is now a new release that 1) fixes the duplicate hs.fi problem in HS query URL building and 2) gives an error message in the fetching phase if the URL doesn't exist. 

I tested your query @Xamk-DataLAB and everything seems to be OK now.
