### ISSUE TITLE
Support for Python async(io) functions

### ISSUE THREAD

**Issue by fergusq** [hsci-r/finnish-media-scrapers#7]
I have a program where I'd like to use these scrapers, but it uses asynchronous coroutines instead of threads to do multiple simultaneous queries. Unfortunately the scrapers use requests and selenium, which only work in synchronous functions (they will block the program).

I use asynchronous functions because they are much simpler to use in Python that threads and multiprocessing (in my opinion, synchronization, error handling and eg. limiting number of concurrent requests is easier).

**Comment by jiemakel** [comment]
I'm sort of two minds about this. On the one hand, I want to be mindful of the medias and not make spamming them with concurrent HTTP queries easier (there's already a conservative 1 second average delay between queries in the scripts). On the other hand, I guess this should be left to be up to the user, particularly for programmatic use. 

I'll see if I'll do this just as a familiarization with Python coroutines.

**Comment by fergusq** [comment]
Just to be clear, in my case I'm making multiple simultaneous queries to different sites, not the same site. Having all requests in the same process makes it easier (imo) to synchronize the coroutines so that each site has its own lock so that only one request is made to the site at time.

**Comment by jiemakel** [comment]
This is now implemented in [v1.1.0](https://github.com/hsci-r/finnish-media-scrapers/releases/tag/v1.1.0).
