### ISSUE TITLE
Another issue with HS login

### ISSUE THREAD

**Issue by fergusq** [hsci-r/finnish-media-scrapers#8]
I managed to locate the bug that caused my previous issues with the HS fetcher.

I use the following code:

```python
>>> from selenium import webdriver
>>> driver = webdriver.Firefox()
>>> import finnish_media_scrapers.fetch as fetch
>>> fetch.prepare_session_hs(driver, "sensuroitu", "sensuroitu"); html=fetch.fetch_article_hs(driver, "https://www.hs.fi/hyvinvointi/art-2000008088281.html")
```

It seems that login is still in progress when `fetch_article_hs` is called and fails. I get a paywalled article.

I can solve the issue for myself simply by adding `time.sleep(3)` between the two calls as you are also doing in the `fetch_hs.py` script. However, if you are planning to support calling the function as a Python library instead of from command line, it would be nice if this could be fixed.

**Comment by jiemakel** [comment]
I added an explicit check for the page URL changing after the submit. Hopefully, this is enough to ensure that the requisite login cookies are actually set before allowing the user to navigate elsewhere.
